namespace ERP.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class modifiedrelationshipforbuyerorder : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.BuyerOrderItems", "BuyerOrderId", "dbo.BuyerOrders");
            DropForeignKey("dbo.BuyerOrderItems", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductColors", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductFactoryAllocations", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductImages", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductSKUs", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductOpeningBalances", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.Schemes", "ProductId", "dbo.tblProducts");
            DropIndex("dbo.BuyerOrderItems", new[] { "BuyerOrderId" });
            DropIndex("dbo.BuyerOrderItems", new[] { "ProductId" });
            DropIndex("dbo.ProductColors", new[] { "ProductId" });
            DropIndex("dbo.ProductFactoryAllocations", new[] { "ProductId" });
            DropIndex("dbo.ProductImages", new[] { "ProductId" });
            DropIndex("dbo.ProductSKUs", new[] { "ProductId" });
            DropIndex("dbo.ProductOpeningBalances", new[] { "ProductId" });
            DropIndex("dbo.Schemes", new[] { "ProductId" });
            //DropPrimaryKey("dbo.BuyerOrderItems");
            //DropPrimaryKey("dbo.BuyerOrders");
            DropPrimaryKey("dbo.tblProducts");
            DropPrimaryKey("dbo.ProductColors");
            DropPrimaryKey("dbo.ProductFactoryAllocations");
            DropPrimaryKey("dbo.ProductImages");
            DropPrimaryKey("dbo.ProductOpeningBalances");
            AddColumn("dbo.BuyerOrderItems", "FinYearId", c => c.Int(nullable: false));
           // AddColumn("dbo.BuyerOrderItems", "BuyerOrderNo", c => c.String());
            AddColumn("dbo.BuyerOrderItems", "ProductSkuID", c => c.Int());
            AddColumn("dbo.BuyerOrderItems", "TaxAmount", c => c.Single(nullable: false));
            AddColumn("dbo.BuyerOrderItems", "FactoryID", c => c.Int(nullable: false));
            AddColumn("dbo.BuyerOrderItems", "BuyerOrder_BuyerID", c => c.Long());
            AddColumn("dbo.BuyerOrderItems", "BuyerOrder_FinYearId", c => c.Int());
            AddColumn("dbo.BuyerOrderItems", "BuyerOrder_BuyerOrderNo", c => c.String(maxLength: 50));
            AddColumn("dbo.BuyerOrders", "TentativeOrderDate", c => c.DateTime());
            //AlterColumn("dbo.BuyerOrderItems", "ID", c => c.Long(nullable: false, identity: true));
            //AlterColumn("dbo.BuyerOrderItems", "BuyerOrderId", c => c.Long(nullable: false));
           // AlterColumn("dbo.BuyerOrderItems", "ProductId", c => c.Long(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "UnitPrice", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "MRP", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "Quintity", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "SchemeFreeQty", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalOrderQty", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalOrderAmt", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalSchemeFreeAmt", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "DiscPercentage", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "DiscAmount", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TaxPercentage", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalOrderCost", c => c.Single(nullable: false));
            AlterColumn("dbo.BuyerOrders", "ID", c => c.Long(nullable: false, identity: true));
            //AlterColumn("dbo.BuyerOrders", "BuyerOrderNo", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.BuyerOrders", "CreationDate", c => c.DateTime());
            AlterColumn("dbo.BuyerOrders", "LastmodifiedDate", c => c.DateTime());
            AlterColumn("dbo.tblProducts", "ProductID", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ProductColors", "ID", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ProductColors", "ProductId", c => c.Long());
            AlterColumn("dbo.ProductFactoryAllocations", "ID", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ProductFactoryAllocations", "ProductId", c => c.Long(nullable: false));
            AlterColumn("dbo.ProductImages", "ID", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ProductImages", "ProductId", c => c.Long());
            AlterColumn("dbo.ProductSKUs", "ProductId", c => c.Long());
            AlterColumn("dbo.ProductOpeningBalances", "ID", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ProductOpeningBalances", "ProductId", c => c.Long());
            AlterColumn("dbo.Schemes", "ProductId", c => c.Long());
            AlterColumn("dbo.Schemes", "SOQtyLimit", c => c.Single(nullable: false));
            AlterColumn("dbo.Schemes", "EveryPeriodforQty", c => c.Single(nullable: false));
            AlterColumn("dbo.Schemes", "FreeQty", c => c.Single(nullable: false));
            //AddPrimaryKey("dbo.BuyerOrderItems", new[] { "BuyerOrderId", "ProductId" });
            //AddPrimaryKey("dbo.BuyerOrders", new[] { "BuyerID", "FinYearId", "BuyerOrderNo" });
            AddPrimaryKey("dbo.tblProducts", "ProductID");
            AddPrimaryKey("dbo.ProductColors", "ID");
            AddPrimaryKey("dbo.ProductFactoryAllocations", "ID");
            AddPrimaryKey("dbo.ProductImages", "ID");
            AddPrimaryKey("dbo.ProductOpeningBalances", "ID");
            CreateIndex("dbo.BuyerOrderItems", "ProductId");
            CreateIndex("dbo.BuyerOrderItems", new[] { "BuyerOrder_BuyerID", "BuyerOrder_FinYearId", "BuyerOrder_BuyerOrderNo" });
            CreateIndex("dbo.ProductSKUs", "ProductId");
            CreateIndex("dbo.ProductColors", "ProductId");
            CreateIndex("dbo.ProductFactoryAllocations", "ProductId");
            CreateIndex("dbo.ProductImages", "ProductId");
            CreateIndex("dbo.ProductOpeningBalances", "ProductId");
            CreateIndex("dbo.Schemes", "ProductId");
            AddForeignKey("dbo.BuyerOrderItems", new[] { "BuyerOrder_BuyerID", "BuyerOrder_FinYearId", "BuyerOrder_BuyerOrderNo" }, "dbo.BuyerOrders", new[] { "BuyerID", "FinYearId", "BuyerOrderNo" });
            AddForeignKey("dbo.ProductSKUs", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.BuyerOrderItems", "ProductId", "dbo.tblProducts", "ProductID", cascadeDelete: true);
            AddForeignKey("dbo.ProductColors", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.ProductFactoryAllocations", "ProductId", "dbo.tblProducts", "ProductID", cascadeDelete: true);
            AddForeignKey("dbo.ProductImages", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.ProductOpeningBalances", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.Schemes", "ProductId", "dbo.tblProducts", "ProductID");
            DropColumn("dbo.BuyerOrderItems", "ProductName");
            DropColumn("dbo.BuyerOrderItems", "UnitId");
            DropColumn("dbo.BuyerOrderItems", "SalesTaxAmount");
            DropColumn("dbo.BuyerOrders", "BuyerOrderTrackerStatusId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.BuyerOrders", "BuyerOrderTrackerStatusId", c => c.Int(nullable: false));
            AddColumn("dbo.BuyerOrderItems", "SalesTaxAmount", c => c.Int(nullable: false));
            AddColumn("dbo.BuyerOrderItems", "UnitId", c => c.Int(nullable: false));
            AddColumn("dbo.BuyerOrderItems", "ProductName", c => c.String());
            DropForeignKey("dbo.Schemes", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductOpeningBalances", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductImages", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductFactoryAllocations", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductColors", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.BuyerOrderItems", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.ProductSKUs", "ProductId", "dbo.tblProducts");
            DropForeignKey("dbo.BuyerOrderItems", new[] { "BuyerOrder_BuyerID", "BuyerOrder_FinYearId", "BuyerOrder_BuyerOrderNo" }, "dbo.BuyerOrders");
            DropIndex("dbo.Schemes", new[] { "ProductId" });
            DropIndex("dbo.ProductOpeningBalances", new[] { "ProductId" });
            DropIndex("dbo.ProductImages", new[] { "ProductId" });
            DropIndex("dbo.ProductFactoryAllocations", new[] { "ProductId" });
            DropIndex("dbo.ProductColors", new[] { "ProductId" });
            DropIndex("dbo.ProductSKUs", new[] { "ProductId" });
            DropIndex("dbo.BuyerOrderItems", new[] { "BuyerOrder_BuyerID", "BuyerOrder_FinYearId", "BuyerOrder_BuyerOrderNo" });
            DropIndex("dbo.BuyerOrderItems", new[] { "ProductId" });
            DropPrimaryKey("dbo.ProductOpeningBalances");
            DropPrimaryKey("dbo.ProductImages");
            DropPrimaryKey("dbo.ProductFactoryAllocations");
            DropPrimaryKey("dbo.ProductColors");
            DropPrimaryKey("dbo.tblProducts");
            DropPrimaryKey("dbo.BuyerOrders");
            DropPrimaryKey("dbo.BuyerOrderItems");
            AlterColumn("dbo.Schemes", "FreeQty", c => c.Int(nullable: false));
            AlterColumn("dbo.Schemes", "EveryPeriodforQty", c => c.Int(nullable: false));
            AlterColumn("dbo.Schemes", "SOQtyLimit", c => c.Int(nullable: false));
            AlterColumn("dbo.Schemes", "ProductId", c => c.Int());
            AlterColumn("dbo.ProductOpeningBalances", "ProductId", c => c.Int());
            AlterColumn("dbo.ProductOpeningBalances", "ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ProductSKUs", "ProductId", c => c.Int());
            AlterColumn("dbo.ProductImages", "ProductId", c => c.Int());
            AlterColumn("dbo.ProductImages", "ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ProductFactoryAllocations", "ProductId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProductFactoryAllocations", "ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ProductColors", "ProductId", c => c.Int());
            AlterColumn("dbo.ProductColors", "ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.tblProducts", "ProductID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.BuyerOrders", "LastmodifiedDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.BuyerOrders", "CreationDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.BuyerOrders", "BuyerOrderNo", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrders", "ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.BuyerOrderItems", "TotalOrderCost", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TaxPercentage", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "DiscAmount", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "DiscPercentage", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalSchemeFreeAmt", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalOrderAmt", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "TotalOrderQty", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "SchemeFreeQty", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "Quintity", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "MRP", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "UnitPrice", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "ProductId", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "BuyerOrderId", c => c.Int(nullable: false));
            AlterColumn("dbo.BuyerOrderItems", "ID", c => c.Int(nullable: false, identity: true));
            DropColumn("dbo.BuyerOrders", "TentativeOrderDate");
            DropColumn("dbo.BuyerOrderItems", "BuyerOrder_BuyerOrderNo");
            DropColumn("dbo.BuyerOrderItems", "BuyerOrder_FinYearId");
            DropColumn("dbo.BuyerOrderItems", "BuyerOrder_BuyerID");
            DropColumn("dbo.BuyerOrderItems", "FactoryID");
            DropColumn("dbo.BuyerOrderItems", "TaxAmount");
            DropColumn("dbo.BuyerOrderItems", "ProductSkuID");
            DropColumn("dbo.BuyerOrderItems", "BuyerOrderNo");
            DropColumn("dbo.BuyerOrderItems", "FinYearId");
            AddPrimaryKey("dbo.ProductOpeningBalances", "ID");
            AddPrimaryKey("dbo.ProductImages", "ID");
            AddPrimaryKey("dbo.ProductFactoryAllocations", "ID");
            AddPrimaryKey("dbo.ProductColors", "ID");
            AddPrimaryKey("dbo.tblProducts", "ProductID");
            AddPrimaryKey("dbo.BuyerOrders", "ID");
            AddPrimaryKey("dbo.BuyerOrderItems", "ID");
            CreateIndex("dbo.Schemes", "ProductId");
            CreateIndex("dbo.ProductOpeningBalances", "ProductId");
            CreateIndex("dbo.ProductSKUs", "ProductId");
            CreateIndex("dbo.ProductImages", "ProductId");
            CreateIndex("dbo.ProductFactoryAllocations", "ProductId");
            CreateIndex("dbo.ProductColors", "ProductId");
            CreateIndex("dbo.BuyerOrderItems", "ProductId");
            CreateIndex("dbo.BuyerOrderItems", "BuyerOrderId");
            AddForeignKey("dbo.Schemes", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.ProductOpeningBalances", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.ProductSKUs", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.ProductImages", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.ProductFactoryAllocations", "ProductId", "dbo.tblProducts", "ProductID", cascadeDelete: true);
            AddForeignKey("dbo.ProductColors", "ProductId", "dbo.tblProducts", "ProductID");
            AddForeignKey("dbo.BuyerOrderItems", "ProductId", "dbo.tblProducts", "ProductID", cascadeDelete: true);
            AddForeignKey("dbo.BuyerOrderItems", "BuyerOrderId", "dbo.BuyerOrders", "ID", cascadeDelete: true);
        }
    }
}
